-- Step 01: Create the database, schema, file format, and stage.
-- Run this before uploading artifacts/processed/documents.jsonl.

CREATE OR REPLACE DATABASE BREAST_CANCER_SEARCH;
CREATE OR REPLACE SCHEMA BREAST_CANCER_SEARCH.RAG;

CREATE OR REPLACE FILE FORMAT BREAST_CANCER_SEARCH.RAG.JSONL_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

CREATE OR REPLACE STAGE BREAST_CANCER_SEARCH.RAG.BREAST_CANCER_STAGE
  FILE_FORMAT = BREAST_CANCER_SEARCH.RAG.JSONL_FORMAT;

-- Next manual step:
-- Upload artifacts/processed/documents.jsonl to @BREAST_CANCER_SEARCH.RAG.BREAST_CANCER_STAGE.

