-- Step 02: Create the raw document table.
-- This table stores one normalized document per source record.

CREATE OR REPLACE TABLE BREAST_CANCER_SEARCH.RAG.RAW_DOCUMENTS (
  DOCUMENT_ID STRING,
  SOURCE_NAME STRING,
  SOURCE_TIER NUMBER,
  SOURCE_URL STRING,
  DOCUMENT_TYPE STRING,
  AUDIENCE STRING,
  TOPIC STRING,
  JURISDICTION STRING,
  TITLE STRING,
  NCT_ID STRING,
  TRIAL_STATUS STRING,
  TRIAL_PHASE STRING,
  CONDITIONS STRING,
  COUNTRIES STRING,
  PMID STRING,
  DOI STRING,
  JOURNAL STRING,
  PUBLICATION_DATE STRING,
  PUBLICATION_TYPES STRING,
  FETCHED_AT TIMESTAMP_TZ,
  CONTENT STRING,
  RAW VARIANT
);

