-- Step 04: Create Snowflake-native text chunks.
-- Production chunking happens in Snowflake, not Python.

CREATE OR REPLACE TABLE BREAST_CANCER_SEARCH.RAG.DOCUMENT_CHUNKS AS
SELECT
  SHA2_HEX(raw.DOCUMENT_ID || ':' || chunk.INDEX::STRING || ':' || chunk.VALUE::STRING, 256) AS CHUNK_ID,
  raw.DOCUMENT_ID,
  chunk.INDEX AS CHUNK_INDEX,
  raw.SOURCE_NAME,
  raw.SOURCE_TIER,
  raw.SOURCE_URL,
  raw.DOCUMENT_TYPE,
  raw.AUDIENCE,
  raw.TOPIC,
  raw.JURISDICTION,
  raw.TITLE,
  raw.NCT_ID,
  raw.TRIAL_STATUS,
  raw.TRIAL_PHASE,
  raw.CONDITIONS,
  raw.COUNTRIES,
  raw.PMID,
  raw.DOI,
  raw.JOURNAL,
  raw.PUBLICATION_DATE,
  raw.PUBLICATION_TYPES,
  raw.FETCHED_AT,
  chunk.VALUE::STRING AS CONTENT
FROM BREAST_CANCER_SEARCH.RAG.RAW_DOCUMENTS raw,
LATERAL FLATTEN(
  INPUT => SNOWFLAKE.CORTEX.SPLIT_TEXT_RECURSIVE_CHARACTER(raw.CONTENT, 'none', 1800, 250)
) chunk
WHERE LENGTH(TRIM(chunk.VALUE::STRING)) >= 80;

SELECT
  'DOCUMENT_CHUNKS_CREATED' AS CHECK_NAME,
  COUNT(*) AS ROW_COUNT
FROM BREAST_CANCER_SEARCH.RAG.DOCUMENT_CHUNKS;

