-- Step 05: Create the Cortex Search service.
-- Change WAREHOUSE if your account uses a different warehouse than COMPUTE_WH.

CREATE OR REPLACE CORTEX SEARCH SERVICE BREAST_CANCER_SEARCH.RAG.BREAST_CANCER_CORTEX_SEARCH
  ON CONTENT
  ATTRIBUTES SOURCE_NAME, SOURCE_TIER, DOCUMENT_TYPE, AUDIENCE, TOPIC, JURISDICTION, SOURCE_URL, TITLE, NCT_ID, TRIAL_STATUS, TRIAL_PHASE, CONDITIONS, COUNTRIES, PMID, DOI, JOURNAL, PUBLICATION_DATE, PUBLICATION_TYPES
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 day'
AS (
  SELECT
    CHUNK_ID,
    DOCUMENT_ID,
    CHUNK_INDEX,
    SOURCE_NAME,
    SOURCE_TIER,
    SOURCE_URL,
    DOCUMENT_TYPE,
    AUDIENCE,
    TOPIC,
    JURISDICTION,
    TITLE,
    NCT_ID,
    TRIAL_STATUS,
    TRIAL_PHASE,
    CONDITIONS,
    COUNTRIES,
    PMID,
    DOI,
    JOURNAL,
    PUBLICATION_DATE,
    PUBLICATION_TYPES,
    CONTENT
  FROM BREAST_CANCER_SEARCH.RAG.DOCUMENT_CHUNKS
);

SHOW CORTEX SEARCH SERVICES LIKE 'BREAST_CANCER_CORTEX_SEARCH'
  IN SCHEMA BREAST_CANCER_SEARCH.RAG;

